services:
  - type: web
    name: satellite-classifier
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    envVars:
      - key: MAPBOX_ACCESS_TOKEN
        value: YOUR_MAPBOX_ACCESS_TOKEN
